# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

commands:
  test-nodejs:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Compile typescript
          command: npm run build
      - run:
          name: Codecov
          command: npm i -g codecov
      - run:
          name: Test
          command: npm test && codecov
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - save-npm-cache
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  test-nodejs-v6:
    steps:
      - run:
          name: Versions
          command: npm version
      - checkout
      - restore_cache:
          keys:
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-master-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}
            - v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-master-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Compile typescript
          command: npm run build
      - run:
          name: Codecov
          command: npm i -g codecov
      - run:
          name: Test
          command: npm test && codecov
          environment:
            JEST_JUNIT_OUTPUT: "reports/junit/js-test-results.xml"
      - save-npm-lock
      - save-npm-cache
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
  save-npm-lock:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-lock-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
  save-npm-cache:
    steps:
      - save_cache:
          key: v{{ .Environment.CIRCLE_CACHE_VERSION }}-{{ arch }}-npm-cache-{{ .Branch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm/_cacache

jobs:
  node-v10:
    docker:
      - image: node:10
      - image: circleci/redis:6.0.4-alpine3.11
    steps:
      - test-nodejs
  node-v12:
    docker:
      - image: node:12
      - image: circleci/redis:6.0.4-alpine3.11
    steps:
      - test-nodejs
  node-v14:
    docker:
      - image: node:14
      - image: circleci/redis:6.0.4-alpine3.11
    steps:
      - test-nodejs
  node-v16:
    docker:
      - image: node:16
      - image: circleci/redis:6.0.4-alpine3.11
    steps:
      - test-nodejs

workflows:
  node-multi-build:
    jobs:
      - node-v10
      - node-v12
      - node-v14
      - node-v16